app:
    resource: '@AppBundle/Controller/'
    type: annotation

luckynumberSmallNumbers:
    path:      /lucky/number/{max}
    defaults:  { _controller: AppBundle:Lucky:smallNumber, max: 10}
    requirements:
       max: ^0*([0-9]|10)$

luckynumberBigNumbers:
    path:      /lucky/number/{max}
    defaults:  { _controller: AppBundle:Lucky:bigNumber, max: 10}
    requirements:
        max: ^0*([1-9]{1,}[0-9]{1,})$
